### ISSUE TITLE
Import existing members bio/title data to main page

### ISSUE THREAD

**Issue by rngadam** [codersfield/candra#33]
Goal is to provide a managed members list
- [x] Import from: http://www.coderbunker.com/members
- [x] Remove insecure and add matching publish/subscribe instead
- [x] Add server-side methods to update/insert/delete users object
- [x] Deploy on public server #41 
- [x] modify Strikingly page to embed #42
- [x] cache/backup profile images #43

**Comment by rngadam** [comment]
moved remaining todo to separate issues.
